# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

bioc_packages:
  - DESeq2
  - ComplexHeatmap
  - biomaRt
  
env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - ASAN="-fsanitize=address -fno-omit-frame-pointer"
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - HDF5_VERSION=1.8.17
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"

before_install: 
  - chmod +x travis_setup.sh
  - ./travis_setup.sh
  
before_deploy: Rscript -e 'install.packages("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
  skip_cleanup: true
